import AboutSection from "@/components/AboutSection";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import PortfolioSection from "@/components/PortfolioSection";
import Head from "next/head";
import { useRef } from "react";

export default function Home() {
  const aboutSectionRef = useRef<HTMLDivElement>(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header invertRefs={[aboutSectionRef]} />
      <HeroSection />
      <AboutSection ref={aboutSectionRef} />
      <PortfolioSection />
      <Footer />
    </>
  );
}
